repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --allow-multiple-documents
          - --unsafe
      - id: check-added-large-files
      - id: check-symlinks
      - id: mixed-line-ending
        args:
          - --fix=lf
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-imports
        exclude: ".*\\.pb\\.go$"
      - id: go-cyclo
        args:
          - -over=30
        exclude: "internal/persistence/ent/.*"
      - id: no-go-testing
      - id: go-mod-tidy
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        exclude: "^etc/config.yaml$"
